---
abstract: 'Compress response body with Gzip or Deflate'
author:
  - 'Tatsuhiko Miyagawa'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Deflater
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  IO::Compress::Deflate: 0
  IO::Compress::Gzip: 0
  Plack: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/Plack-Middleware-Deflater.git
version: 0.05
